- bundle.js
Keep the headers when converting `bundle.request` from CLI to WB scripting.
This is to address the need to run middlewares on the app level. Refer to zapier/zapier-platform-cli#271.
> Keep whatever headers passed into runEvent

- bundle.js
Keep `request.params` when converting `bundle.request` from CLI to WB scripting. Almost the identical to PR #1, but for `request.params`.
This is to address the need to run middlewares on the app level. Refer to zapier/zapier-platform-cli#271.
> Keep request.params passed into runEvent

- index.js
Adds support for running `get_session_info()`scripting method with `z.legacyScripting.run(bundle, 'auth.session')`. Test can be found [here](https://github.com/zapier/zapier-platform-core/pull/86/files#diff-df07f23506acd426532e246a617346c6R36).
> Legacy Scripting: Add support for session auth

- index.js
Makes whatever `get_session_info()` returns available in `bundle.authData`. Turns out we were over-engineering session auth. CLI doesn't have that single key constraint for session auth.
> Include entire session data, not just single key

- index.js
- package-lock.json
- package.json
- test/example-app/index.js
- test/example-app/session-auth.js
- test/integration-test.js
Removes legacy scripting tests from `core` (see https://github.com/zapier/zapier-platform-core/pull/96) to `legacy-scripting-runner`. The dependencies (`async` and `moment-timezone` etc) that we used to require in converted app's are now required by `legacy-scripting-runner` directly.
> Move legacy scripting tests out of core

- index.js
Adds the ability to compile legacy scripting source from a string so `core` [doesn't have to](https://github.com/zapier/zapier-platform-core/pull/98).
> Ability to compile source

- .travis.yml
- bundle.js
- index.js
- package-lock.json
- package.json
- test/example-app/index.js
- test/example-app/oauth2.js
- test/example-app/session-auth.js
- test/integration-test.js
Allows to run OAuth2 scripting with `z.legacyScripting.run(bundle, 'auth.oauth2.token')` and `z.legacyScripting.run(bundle, 'auth.oauth2.refresh')`.
Also refactors and bumps Node version to 8.10.0.
> Ability to run OAuth2 scripting

- bundle.js
- index.js
- test/example-app/api-key-auth.js
- test/example-app/index.js
- test/integration-test.js
In CLI, `z.request` invokes `beforeRequest` middleware under the hood to do authentication. In WB scripting, however, `z.request` doesn't have any of that magic. Instead, WB backend sets the auth data into `bundle.request` and passes it to a scripting method.
This PR simulates this behavior by applying `beforeRequest` middleware to `bundle.request` before it gets passed to a scripting method. The trigger tests are updated to reflect the change.
> Apply beforeRequest middleware to bundle.request before calling scripting methods

- index.js
- test/example-app/index.js
- test/integration-test.js
Adds support for `KEY_pre_custom_trigger_fields` and `KEY_post_custom_trigger_fields`, which can be invoked by `z.legacyScripting.run(bundle, 'trigger.output', 'KEY')` in a CLI app definition.
Note that this PR uses https://auth-json-server.zapier.ninja/output-fields?api_key=secret to test custom output fields.
> KEY_(pre|post)_custom_trigger_fields

- index.js
- test/example-app/index.js
- test/integration-test.js
Adds support for action scripting: `KEY_pre_write`, `KEY_post_write`, and `KEY_write`, allowing running action scripting methods by invoking `z.legacyScripting.run(bundle, 'create', 'KEY')`.
> KEY_pre_write, KEY_post_write, KEY_write

- index.js
- test/example-app/index.js
- test/integration-test.js
Adds support for search custom fields scripting, i.e., the following scripting methods:
```
KEY_pre_custom_search_fields
KEY_post_custom_search_fields
KEY_custom_search_fields
KEY_pre_custom_search_result_fields
KEY_post_custom_search_result_fields
KEY_custom_search_result_fields
```
Reuses a lot of things that were already done in #20.
> Search custom fields scripting

- bundle.js
- index.js
- test/auth-json-server.js
- test/example-app/api-key-auth.js
- test/example-app/index.js
- test/example-app/oauth2.js
- test/integration-test.js
Adds support for the following search scripting methods:
```
KEY_pre_search
KEY_post_search
KEY_search
KEY_pre_read_resource
KEY_post_read_resource
KEY_read_resource
```
This allows us to run the search scripting by calling `z.legacyScripting.run(bundle, 'search', 'KEY')` and `z.legacyScripting.run(bundle, 'search.resource', 'KEY')` in a CLI app.
Also replaces all occurrences of `https://auth-json-server.zapier.ninja` with `AUTH_JSON_SERVER_URL` constant, making it possible to test with a local hosted [auth-json-server](https://github.com/zapier/auth-json-server).
> Search scripting

- exceptions.js
- index.js
- test/example-app/index.js
- test/integration-test.js
- test/zfactory.js
- z.js
- zfactory.js
Implements `z.dehydrateFile` conversion. There's some code auto-formatting noise in PR, but this is how it's going to work:
* WB scripting `z.dehydrateFile(url, request, meta)` is converted to CLI `z.dehydrateFile(hydrators.legacyFileHydrator, { url, request, meta })`.
* Every converted app will have a `hydrators.legacyFileHydrator` in their app definition. The work is done in https://github.com/zapier/zapier/pull/19418.
* `hydrators.legacyFileHydrator` calls `z.legacyScripting.run(bundle, 'hydrate.file')`, which calls into `runHydrateFile` in this PR.
* `runHydrateFile` does typical CLI file hydration that involves `z.stashFile`. It also simulates WB behavior where we don't send auth data when `request` argument isn't provided in `z.dehydrateFile`. This PR has tests to confirm that.
Some …
> Add support for z.dehydrateFile

- bundle.js
- index.js
- test/example-app/index.js
- test/integration-test.js
- zfactory.js
Implements the conversion for `z.dehydrate`. This works a lot like `z.dehydrateFile` conversion (#24). That is:
* All converted apps will have a hydrator named `hydrators.legacyMethodHydrator` that simply returns `z.legacyScripting.run(bundle, 'hydrate.method')`. This is done in https://github.com/zapier/zapier/pull/20722.
* Legacy WB scripting's `z.dehydrate(methodName, legacyBundle)` is translated to CLI's `z.dehydrate(hydrators.legacyMethodHydrator, { method: methodName, bundle: legacyBundle })`.
* `z.legacyScripting.run(bundle, 'hydrate.method')` calls `runHydrateMethod`, which then calls the actual hydrator in the legacy scripting, such as `Zap.get_user`.
This PR depends on the latest work in core that hasn't been published to npm. It's expected to fail on Travis. We can only run …
> Convert z.dehydrate

- index.js
- test/example-app/index.js
- test/example-app/oauth2.js
- test/integration-test.js
Addresses [PDE-538](https://zapierorg.atlassian.net/browse/PDE-538). Moves all the `legacyProperties` into a root prop `legacy` in the app definition. This requires https://github.com/zapier/zapier-platform-core/pull/132 to pass the tests.
> Re-org legacy props

- $.js
- package-lock.json
- package.json
- test/example-app/index.js
- test/integration-test.js
Fixes [PDE-554](https://zapierorg.atlassian.net/browse/PDE-554). Previously, only `$.param` and `$.parseXML` are available. This PR adds a new dependency `jquery`, so devs can use `$` full functionalities in their scripting.
>  Make jQuery $ function available in scripting

- index.js
- package-lock.json
- package.json
- test/example-app/index.js
- test/integration-test.js
Addresses [PDE-603](https://zapierorg.atlassian.net/browse/PDE-603), where we should use [Underscore](https://underscorejs.org/) instead of [Lodash](https://lodash.com/) for legacy scripting. 
Originally, to keep the package size small, I was thinking we can make an Underscore shim that calls Lodash under the hood. But it turned out adding an `underscore@1.4.4` dependency doesn't increase the size that much. Before and after are 3,459 and 3,477 KB, only a 0.5% increase.
> Use underscore instead of lodash

- test/example-app/index.js
- test/integration-test.js
Part of [PDE-606](https://zapierorg.atlassian.net/browse/PDE-606) and [PDE-727](https://zapierorg.atlassian.net/browse/PDE-727).
Adds tests to make sure scripting js is run in sloppy mode by default.
> Add tests for strict mode

- index.js
- test/integration-test.js
Back in #42 we attempted to fix a bug where we wouldn't know for sure if we were doing an auth test or not. At the time, we assumed that if the trigger being run is the test trigger, it's an auth test.
This assumption doesn't hold, however. Some apps use a legitimate polling trigger as the auth test as well. In these situations, any Zap that tries to run with that trigger will return true for the `isTestingAuth` check [here](https://github.com/zapier/zapier-platform-legacy-scripting-runner/blob/40bfd4f922c1e476e460af64a4fe55149a42ca58/index.js#L716-L718), resulting in us plucking out the first item in the list. This in turns causes us to fail the middleware check for triggers returning an array.
This PR nukes the comparison against the test trigger key. We can make an improvement on the …
> Fix issue running polling triggers that double as auth tests

- index.js
- package-lock.json
- package.json
- test/example-app/index.js
- test/integration-test.js
There are several things going on in this PR:
**lodash fix**
Bumped lodash version to fix a security vulnerability alert.
**Test Fixes**
A bunch of tests had broken, I think because of the httpbin move from Heroku to Kubernetes. There's various fixes for these tests to get them to pass.
**needsTriggerData**
The simpler of the two flags that get set during conversion. The backend changes for this were made in https://github.com/zapier/zapier/pull/25412. This just causes `runEventCombo` to set an empty object in the bundle if the flag has been set. 
**needsFlattenedData**
The more complex of the the two flags. The backend changes for this were made in https://github.com/zapier/zapier/pull/25029 and https://github.com/zapier/zapier/pull/25332. This required a port of the `textify_list` and …
> Add needsTriggerData and needsFlattenedData flag support
